version: '3.8'

services:
  backend:
    build: 
      context: ./drive-clone-backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./drive-clone-backend/uploads:/app/uploads:delegated
    environment:
      - NODE_ENV=production
      - JWT_SECRET=your-secret-key
      - CORS_ORIGIN=http://localhost:80
      - MONGODB_URI=mongodb+srv://myAtlasDBUser:6Eziu6ClNR145yFk@cluster0.s3goh4j.mongodb.net/drive-clone?retryWrites=true&w=majority
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./drive-clone-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./drive-clone-frontend/build:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge