version: '3.8'

services:
  backend:
    build: 
      context: ./drive-clone-backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./drive-clone-backend/uploads:/app/uploads:delegated
    environment:
      - NODE_ENV=production
      - JWT_SECRET=your-secret-key-here
      - CORS_ORIGIN=http://localhost:80
      - MONGODB_URI=mongodb://mongo:27017/drive-clone
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: ./drive-clone-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./drive-clone-frontend/build:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 3

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    name: drive_clone_mongodb_data
    driver: local